### ISSUE TITLE
404 error while adding dependency in test files

### ISSUE THREAD

**Issue by PratibhaP** [ggalmazor/pft-angularjs-requirejs#1]
I have Following project structure
src >
-- main
--- webapp
---- js
----- controller
----- lib
----- service
...
-- test
--- webapp
---- tests
----- ctrl_test.js
--- karma.conf.js
--- package.json
--- test-main.js

when, I write test case for ctrl

define(['angular', 'app'], function(angular, app){
describe('XYZ Controller', function () { ------- }); });

Getting following error in cmd -

20 08 2018 13:56:08.950:WARN [web-server]: 404: /base/src/main/webapp/js/app.js
20 08 2018 13:56:08.954:WARN [web-server]: 404: /base/src/main/webapp/js/lib/angular.min.js

What is wrong in my code? please help me to figure it out

**Comment by ggalmazor** [comment]
Hi, @PratibhaP!

I'm sorry, but this project is already 5 years old. Everything on it is pretty much obsolete, please don't use it as scaffolding, or, if you want to learn how to do testing with web apps in Angular, use a newer resource.
